In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv("penguins_data.csv")

In [3]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7                181   
1  Adelie  Torgersen            39.5           17.4                186   
2  Adelie  Torgersen            40.3           18.0                195   
3  Adelie  Torgersen            36.7           19.3                193   
4  Adelie  Torgersen            39.3           20.6                190   

   body_mass_g     sex  
0         3750    male  
1         3800  female  
2         3250  female  
3         3450  female  
4         3650    male

# Encoding Features

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le=LabelEncoder()

In [6]:
from pandas.core.dtypes.common import is_numeric_dtype

In [7]:
for i in df.columns:
    if is_numeric_dtype(df[i]):
        continue
    else:
        df[i]=le.fit_transform(df[i])

In [8]:
df.head(10)

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2            39.1           18.7                181   
1        0       2            39.5           17.4                186   
2        0       2            40.3           18.0                195   
3        0       2            36.7           19.3                193   
4        0       2            39.3           20.6                190   
5        0       2            38.9           17.8                181   
6        0       2            39.2           19.6                195   
7        0       2            41.1           17.6                182   
8        0       2            38.6           21.2                191   
9        0       2            34.6           21.1                198   

   body_mass_g  sex  
0         3750    1  
1         3800    0  
2         3250    0  
3         3450    0  
4         3650    1  
5         3625    0  
6         4675    1  
7         3200    0  
8         3800    1  
9         4400    1

# Split Dataset

In [9]:
x=df.drop("species",axis=1)

In [10]:
x.head()

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex
0       2            39.1           18.7                181         3750    1
1       2            39.5           17.4                186         3800    0
2       2            40.3           18.0                195         3250    0
3       2            36.7           19.3                193         3450    0
4       2            39.3           20.6                190         3650    1

In [11]:
y=df[["species"]]
y.head()

species
0        0
1        0
2        0
3        0
4        0

# Train the dataset

In [12]:
from sklearn.model_selection import train_test_split as tts

In [13]:
xtrain,xtest,ytrain,ytest=tts(x,y,test_size=0.3,random_state=44)

In [14]:
xtrain.head()

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
45        0            40.1           18.9                188         4300   
206       0            46.2           14.9                221         5300   
102       0            38.1           17.0                181         3175   
114       2            36.2           17.2                187         3150   
122       2            39.0           17.1                191         3050   

     sex  
45     1  
206    1  
102    0  
114    0  
122    0

In [15]:
ytest.head()

species
332        1
137        0
322        1
243        2
107        0

# Classification Algorithm

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
clf=RandomForestClassifier()

In [18]:
clf.fit(xtrain,ytrain)

C:\Users\USER\AppData\Local\Temp\ipykernel_2572\3000261254.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(xtrain,ytrain)


RandomForestClassifier()

In [19]:
clf.score(xtest,ytest)

0.98

In [20]:
pred=clf.predict(xtest)

In [21]:
r2_score(ytest,pred)

0.9746031746031746

# Save model

In [22]:
import pickle as pk

In [23]:
pk.dump(clf,open("penguin_project","wb"))

In [24]:
clf2=pk.load(open("penguin_project","rb"))

In [25]:
clf2.predict([[0,40.1,18.9,188,4300,1]])

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [26]:
xtest.head()

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
332       1            50.2           18.7                198         3775   
137       1            40.7           17.0                190         3725   
322       1            49.3           19.9                203         4050   
243       0            51.1           16.5                225         5250   
107       0            42.2           19.5                197         4275   

     sex  
332    0  
137    1  
322    1  
243    1  
107    1

In [27]:
clf2.predict([[1,50.2,18.7,198,3775,0]])

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [28]:
import joblib as jb

In [29]:
jb.dump(clf,'penguin_project2')

['penguin_project2']

In [30]:
rf=jb.load('penguin_project2')

In [31]:
rf.predict([[1,50.2,18.7,198,3775,0]])

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])